import json
from pathlib import Path

root = Path(r"D:\Project_Portofolio\supply-chain-risk-intelligence")
nb = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Supply Chain Risk Intelligence — EDA Notebook\n",
                "\n",
                "This notebook documents the exploratory analysis layer for the portfolio project. It uses the cleaned dataset generated by `scripts/prepare_data.py` and the KPI marts under `data/marts/`.\n"
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Analysis questions\n",
                "\n",
                "1. How large is the late delivery risk problem?\n",
                "2. Which shipping modes and markets carry the highest risk?\n",
                "3. Which categories drive sales and profit?\n",
                "4. Where do high revenue and weak margins overlap?\n",
                "5. How should the ML result be interpreted for operations?\n"
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from pathlib import Path\n",
                "import json\n",
                "import pandas as pd\n",
                "\n",
                "ROOT = Path('..')\n",
                "MARTS = ROOT / 'data' / 'marts'\n",
                "PROCESSED = ROOT / 'data' / 'processed'\n",
                "\n",
                "profile = json.load(open(MARTS / 'data_profile.json', encoding='utf-8'))\n",
                "delivery = pd.read_csv(MARTS / 'delivery_kpis.csv')\n",
                "region_shipping = pd.read_csv(MARTS / 'region_shipping_kpis.csv')\n",
                "category = pd.read_csv(MARTS / 'category_performance.csv')\n",
                "profitability = pd.read_csv(MARTS / 'profitability_kpis.csv')\n",
                "monthly = pd.read_csv(MARTS / 'monthly_delivery_trend.csv')\n",
                "metrics = json.load(open(MARTS / 'model_metrics.json', encoding='utf-8'))\n",
                "\n",
                "profile\n"
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Executive KPI summary\n"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "summary = pd.DataFrame([\n",
                "    {'metric': 'orders', 'value': profile['clean_rows']},\n",
                "    {'metric': 'late_delivery_orders', 'value': profile['late_delivery_orders']},\n",
                "    {'metric': 'late_delivery_rate', 'value': profile['late_delivery_rate']},\n",
                "    {'metric': 'total_sales', 'value': profile['total_sales']},\n",
                "    {'metric': 'total_profit', 'value': profile['total_profit']},\n",
                "    {'metric': 'avg_profit_margin', 'value': profile['avg_profit_margin']},\n",
                "])\n",
                "summary\n"
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Delivery risk by shipping mode\n"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "delivery.sort_values('orders', ascending=False)[['shipping_mode','orders','late_orders','late_rate','avg_shipping_gap','sales','profit']]\n"
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Risk hotspots: market x region x shipping mode\n"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "risk_hotspots = (\n",
                "    region_shipping[region_shipping['orders'] >= 500]\n",
                "    .sort_values(['late_rate','orders'], ascending=[False, False])\n",
                "    .head(15)\n",
                ")\n",
                "risk_hotspots[['market','order_region','shipping_mode','orders','late_rate','avg_shipping_gap','sales','profit']]\n"
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Category performance\n"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "category.sort_values('sales', ascending=False).head(15)[['category_name','department_name','orders','sales','profit','profit_margin','late_rate']]\n"
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## High revenue, low margin segments\n"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "high_rev_low_margin = (\n",
                "    profitability[profitability['orders'] >= 100]\n",
                "    .sort_values(['sales','profit_margin'], ascending=[False, True])\n",
                "    .head(20)\n",
                ")\n",
                "high_rev_low_margin[['market','order_region','category_name','orders','sales','profit','profit_margin','late_rate','avg_discount_rate']]\n"
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Model interpretation\n"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "best = metrics['best_model']\n",
                "pd.DataFrame(metrics['metrics']).T\n"
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Notes for interview storytelling\n",
                "\n",
                "- The project separates historical diagnosis from operational prediction.\n",
                "- Actual shipping days are useful for explaining past performance, but excluded from the operational model to avoid target leakage.\n",
                "- Recall matters because missing a risky shipment is usually more costly than reviewing a safe shipment.\n",
                "- The dashboard uses model scores as a queueing aid, not as an automated SLA decision engine.\n"
            ],
        },
    ],
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}
out = root / "notebooks" / "01_eda_supply_chain.ipynb"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(nb, indent=2), encoding="utf-8")
print(out)
